title: Writtic's forge
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://writtic.github.io/index.html
baseurl: "http://writtic.github.io/index.html"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: https://github.com/Writtic
   twitter: None
   facebook: https://www.facebook.com/Writtic
   email: Writtic@gmail.com

google_analytics: "UA-58263416-1"
